service: code-challenge-5-sg
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
functions:
  create:
    handler: create.handler
    events:
      - http:
          path: users
          method: POST
          cors: true